# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title.html

# Setup
title:               I can't study physics
tagline:             'Suna の house'
description:         '一個會放些有的沒的無聊的blog，其實我只當雲端用'
url:                 https://wtxdew.github.io
baseurl:             ''

paginate:            5
paginate_path: "blog/page:num"

# About/contact
author:
  name:              wtxdew
  url:               https://twitter.com/wt_air
  email:             wt_air@icloud.com

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

sass:
    sass_dir: _sass
    style: compressed

# Custom vars
version:             1.0.0

plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-sitemap

timezone: Asia/Taipei

encoding : utf-8

# Google Analytics
google_analytics: UA-172860566-1
