name: Deploy to Server

on:
  push:
    branches:
      - master # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hep1.phys.ntu.edu.tw
        username: tong
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          cd /home/hep/tong/public_html/homepage && git pull


