name: Deploy to Server

on:
  push:
    branches:
      - master # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to server
      run: |
        ssh -o "StrictHostKeyChecking=no" tong@hep1.phys.ntu.edu.tw "cd /home/hep/tong/public_html/homepage && git pull origin master && deploy from github trigger by push"

